secret_files:
  cert:
    path:  '/etc/pki/tls/certs/ha02.uib.uhdc.no.cert.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  key:
    path:  '/etc/pki/tls/private/ha02.uib.uhdc.no.key.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'

